title: assessment-push
description: A sample assessment for pushing to GitHub.
template:
  repo: assessment-push-template
  name: assessment-push
before:
  - type: createIssue
    title: Feedback
    body: feedback-placeholder.md
steps:
  - title: Push to GitHub
    description: Make a commit to this repository using any tool you wish except GitHub itself. Push that commit to this repository.
    event: push
    link: '{{ repoUrl }}'
    actions:
      - type: gate
        left: '{{ payload.commits.0.committer.username }}'
        operator: '!=='
        right: 'hectorsector'
      - type: gate
        every: true
        gates: 
        - left: '{{ payload.commits.0.committer.name }}'
          operator: ===
          right: 'GitHub'
        - left: '{{ payload.commits.0.committer.email }}'
          operator: ===
          right: 'noreply@github.com'
        - left: '{{ payload.commits.0.committer.username }}'
          operator: ===
          right: 'web-flow'
        else:
          - type: respond
            issue: 1
            with: feedback-success.md
            data:
              thePayload: '{{ payload }}'
      - type: respond
        issue: 1
        with: feedback-fail.md
